# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrentWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # Pods for CurrentWork

end

target 'TodayExWtihFB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodayExWtihFB

  target 'TodayExWtihFBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodayExWtihFBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
